### ISSUE TITLE
Cloud Native Security Whitepaper

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#138]
In 2018, SAFE WG focused on understand security, given modern (cloud native) enterprise infra, and synthesized into a common understanding; however, much of what we have learned is buried in meeting notes and presentations.

We would like to now communicate what we’ve understood to the rest of the world.  One step will be to draft a SAFE whitepaper that covers over-arching concerns.  Some of us met (march 22, 2019) to brainstorm a whitepaper outline:

# Outline:
* Objective
* Audience
* Intro
  * Goals
  * Scope
  * Assumptions
* Cloud Native Layers
  * Environments
  * Lifecycle
* Personas & Use cases
* Security, Compliance & Auditing
* Security Stack
* Evolution
* References

# Current Whitepaper Work in progress:

[Whitepaper ready for review](https://docs.google.com/document/d/1aAkuhZMJ6-Xq6xP0gh1wxIM8OhUETqEFLhoRdxYHN5c/edit?usp=sharing)  Comments are turned on so please comment!

# TO DO
- [X] SIG Chair support: @pragashj 
- [X] Project leader: @TheFoxAtWork 
- [X] small group to review next iteration of outline & define terms starting 7/29 9AM Pacific
- [X] create schedule
- [X] Create [Outline](https://docs.google.com/document/d/1nKM-z-_yCSff2CWxF-lPmiWMtM5M2DgBi-Ztu1FQNSI)
- [x] present draft to SIG (including goals, target audience, in scope / out of scope)
- [x] Solicit intended audience cursory review

# Proposed Schedule:
- [X] _Due AUG 12 2020_
* Tasking Assignment - group members interested in content generation for a particular topic area at the numeric alpha level (1.b for instance) members should place their names in parenthesis next to the title with .  Members with subject matter expertise in areas below numeric alpha and wishing to contribute to that sub-section should include it by their name for the topic area.

- [X] _AUG 12 thru SEP 02 2020_ - *Content rough-in*
* Content Rough-in - group members should begin generating content for the respective areas of assignment. Cohesive sentences, concepts, phrasing, etc. should be placed in quotations ("") for later review as whole content.
* Meeting on AUG 26
* Content rough-in will be pulled into clean working doc after meeting on AUG 26 and shared with group.

- [x] _SEP 02 thru SEP 23 2020_ - *Collaborative review*
* Collaborative review - group members will comment and review initial draft content on clean doc. 
* Meeting on SEP 09 - get a feel for where we are at, add't time needed, any questions, etc. , identify presenters for SEPT 23rd SIG meeting on CNSWP content draft.
* [Link to the Working Draft](https://docs.google.com/document/d/1MEeqWvUavXK5TkuFIfoJbtxCT-2FdTw7jgYP3kxtbmk/edit?usp=sharing)

- [X] _SEP 23 2020 thru OCT 07 2020_ - *executive summary and content wrap up*

- [x] _~OCT 07 thru OCT 19 2020_ *Narrative Voice*
* Narrative Voice and content level - limited review to provide singular narrative voice and ensure content level is in keeping with goals, audience and scope
* no meeting
* SIG Security presentation and overview - unassigned

- [x] _~OCT 19 thru OCT  27 2020_ *Final Group Review*
* Final Review - final review by group, with selected "intended audience"
* Post content to the repo after reviewed?

- [x] _CNCF Editorial Assistance_ - @dshaw @pragashj 

- [ ]_~DUE NOV 04 2020_ (subject to CNCF timeline) *Final adjudication*
* Final adjudication

# Meeting notes for WG syncs
[Meeting note and agenda](https://docs.google.com/document/d/1dQAsC1KgMEnVTnQbBKDaAhYPe90NQawGAAYPzG8_JfA/edit?usp=sharing)

**Comment by ultrasaurus** [comment]
@pragashj @dshaw @ultrasaurus, Jessica Walker and Sara Dornsife met to discuss white paper content - see [3/22/2018 meeting notes](https://docs.google.com/document/d/1NxVDNNOVltrKnbhwil1nu1z3gzi8dSCj1Y6SVXse3DY/edit)

**Comment by ultrasaurus** [comment]
Moved outline into separate doc where we can elaborate into a [full whitepaper](https://docs.google.com/document/d/1BgS6cVfTUtBVhOdvc7J0gGPCZPCEnDxjhUGvqeUt1sY/edit#)

**Comment by rficcaglia** [comment]
just a process question - is it more desirable to use Google Docs vs. markdown docs that can be PR'd? is the idea to minimize git activity until there is a solid draft document rather than have the full "sausage making" process clutter up the git stream?

**Comment by pragashj** [comment]
That is the idea, please feel free to chime in on the doc and help shape it.

**Comment by TheFoxAtWork** [comment]
related #405

**Comment by whaber** [comment]
I would like to participate.  Please include me in future discussions on it.

**Comment by vinayvenkat** [comment]
+1 @vinayvenkat

**Comment by PushkarJ** [comment]
+1 please include me

**Comment by tabbysable** [comment]
+1

**Comment by trishankatdatadog** [comment]
+1

**Comment by dshaw** [comment]
@vinayvenkat @whaber @PushkarJ @tabbysable @trishankatdatadog I have added you all to the new working group Slack channel.

For any other members of SIG-Security who may want to join us, add yourself here then please also ping me on Slack.

**Comment by chasemp** [comment]
Please add me at your convenience to the slack channel.  Thanks @dshaw.

**Comment by gadinaor** [comment]
@dshaw - can you add me to the slack channel please

**Comment by sublimino** [comment]
@dshaw me too please :pray:

**Comment by TheFoxAtWork** [comment]
@gadinaor - i don't see you in the members listing or in the existing slack to add you

**Comment by gadinaor** [comment]
> @gadinaor - i don't see you in the members listing or in the existing slack to add you

@TheFoxAtWork true // I'm part of it now

**Comment by IAXES** [comment]
May I please be added as well? Thank you @dshaw

**Comment by kapilt** [comment]
I'm also interested re slack and discussion on this topic, thanks @dshaw

**Comment by TheFoxAtWork** [comment]
@kapilt i DM'd u in slack, need ur email to get u access, updates are in the channel

**Comment by rowan-baker** [comment]
May I please be added to the slack channel, I am looking to help @sublimino with his contribution. Also raising a PR to join as a member shortly. Thanks @dshaw  / @TheFoxAtWork

**Comment by TheFoxAtWork** [comment]
Updated with new schedule to allow more time for content generation

**Comment by TheFoxAtWork** [comment]
Team is moving forward!  extended the collaborative review by a week to accommodate busy schedules

**Comment by TheFoxAtWork** [comment]
merge https://docs.google.com/document/d/11gyDDsKtMchMlj9ZKDl5LSHNxgu04tq1dTSD1BnTG9o/edit#heading=h.v65lmin9x1eb Issue #20 into the white paper

**Comment by SaadUllahSheikh** [comment]
@ultrasaurus please can you add me to Security white paper i want to give some inputs specially for Telecom perspective , thanks

**Comment by fctoibm** [comment]
Enterprise
Core areas of concern for Enterprise to adopt a cloud-native model are maintaining the current process and procedures while meeting the business objective. Keeping the interoperability, data loss or leakage, and security risk exposure at a minimum when new standards and practices are introduced throughout the organization. 
Microbusiness
Small businesses tend to focus on short term goals and innovation to meet intense competition. The lack of resources, budget, technology depth, and best practice hinders their ability to adapt to cloud-native solutions. Small business requires repeatable patterns and small IT footprint to solve the challenges.  
Finance
  Core areas of concern for financial industries essential to successful cloud-native adoption are unauthorized disclosure of information, fraud, and fund availability. Fraud can directly impact fund availability, making the integrity of financial transactions of paramount importance.  
Healthcare
  Core areas of concern for healthcare industries essential to successful cloud-native adoption are unauthorized disclosure of information, timeliness, availability of records, and records accuracy. Due to the nature and practices of the healthcare industry, the availability of records and their associated content is how medical decisions are made. In the absence of such information, new records are developed.
Academia and education
  Core areas of concern for educational institutions for successful cloud-native adoption can depend upon the intended end user. Institutions catering to minors may have additional legal requirements to protect minors’ confidentiality, thereby making access control critical. Beyond this, institutions should focus on the availability of educational content to end-users.
Public Sector
Core areas of concern for Public Sector organizations to implement cloud-native adoptions are security, data sovereignty, compliances, and vendor lock-in. The barriers emerge from agencies placing regulations to protect the public interest. In the public sector, it is essential to maintain harmony and trust between public and government entities.

**Comment by lumjjb** [comment]
Thanks Harmeet, i'll add them into the doc

**Comment by vinayvenkat** [comment]
Sig-Security meeting on 9/16/2020 White paper update: https://docs.google.com/presentation/d/1JVNMxDAJFbTTmmEwpL5lh_OGajbDfZx5E40YRkg1cV0/edit#slide=id.g97edbdf573_0_48

**Comment by TheFoxAtWork** [comment]
Thanks to everyone who helped make this possible.  The Cloud Native Security Whitepaper now lives in the repo as [Markdown](https://github.com/cncf/sig-security/blob/master/security-whitepaper/cloud-native-security-whitepaper.md).  As significant changes occur, we will republish the PDF by major version.
