### ISSUE TITLE
DockerCon, San Francisco, CA, Apr 30 - May 2, 2019

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#151]
I think there are going to be a few of us at DockerCon and also in the area, let's meet up in the evening.

EDIT: Thursday May 2, 7:30pm at [Mikkeller](https://www.yelp.com/biz/mikkeller-bar-san-francisco).

**Comment by lumjjb** [comment]
I think Wednesday (May 1) and Thursday (May 2) evenings are good times outside the conference schedule. I'm not as familiar with SF compared to others here, so I'm open to suggestions on places to get dinner.

**Comment by justincormack** [comment]
We have an open source security summit on Thursday as part of DockerCon, if anyone from the SIG needs a ticket let me know and I will sort it out...

**Comment by lumjjb** [comment]
Let's set the date as May 1 (Wednesday) then? 

@justincormack, I'd like to join in on that!

**Comment by ultrasaurus** [comment]
I can make it on Wed or Thurs (with Thursday slightly preferred)... I think the open source security summit is just a related Dockercon event, looks like [10a-noon](https://dockercon19.smarteventscloud.com/connect/search.ww#loadSearch-searchPhrase=&searchType=session&tc=0&sortBy=dayTime&i(1037)=196687&dayID=15386&p=) so I don't think it will collide with evening gathering.

Some location options:
* [Thirsty Bear](https://www.yelp.com/biz/thirsty-bear-brewing-company-san-francisco-5) - Spanish tapas, locally brewed beer
* [OSHA Thai](https://www.yelp.com/biz/osha-thai-san-francisco-13) on 3rd -- asian fusion, fun place for groups, more of a sit-down dinner 
* [Mikkeller](https://www.yelp.com/biz/mikkeller-bar-san-francisco) -- huge draft beer selection, limited [menu](https://www.yelp.com/menu/mikkeller-bar-san-francisco/main-menu), good food for meet and cheese lovers, limited vegan options, no reservations, tho that could be a plus, since it's easy to hang out if everyone doesn't arrive all at once

If we want to go a little farther, two of my fave restaurants, both "french vietnamese"
* [Le Colonial](https://www.yelp.com/biz/le-colonial-san-francisco)
* [Slanted Door](https://www.yelp.com/biz/the-slanted-door-san-francisco)

Open to suggestions from other locals or food preferences from visitors

**Comment by justincormack** [comment]
Thursday is better for me, I have another event on Wednesday at 8.30ish. There are always lots of dockercon events at thirsty bear as its next to moscone so I might be tired of it by then. osha thai/mikkeller/slanted door are all lovely, havent tried le coloniel before...

**Comment by lumjjb** [comment]
Lets do Thursday evening then. I agree on the no reservations being a plus :), unless we have dietary restrictions. Tentatively let's set it as Thursday May 2, 7:30pm at [Mikkeller](https://www.yelp.com/biz/mikkeller-bar-san-francisco).

**Comment by lumjjb** [comment]
+ @lizrice

**Comment by lizrice** [comment]
Sounds great but I am flying back to the UK on Thursday

**Comment by lumjjb** [comment]
Meeting up @ DockerCon was awesome!
