### ISSUE TITLE
Define chair election process and role schedule

### ISSUE THREAD

**Issue by lizrice** [cncf/sig-security#251]
I might have missed it, but I couldn't find anything about the election term and schedule for SIG chairs.

**Comment by lizrice** [comment]
The term is covered by the standard SIG operating process here https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md#elections but I think it would be helpful to list the chairs & tech leads on the SIG home page (there is a members list there already), along with their election term.

**Comment by ultrasaurus** [comment]
@lizrice chairs are identified in the README.  We actually forgot to pick who was 1 or 2 year term -- we'll need to draw straws and update.  We did not identify tech lead roles initially, and had focused on establishing a range of ways for people to get involved (see [roles](https://github.com/cncf/sig-security/blob/master/governance/roles.md). 

Since Tech Lead roles have a bit more process (nomination and voting by 2/3 of TOC), we wanted to give people the opportunity to demonstrate their skills and commitment before establishing those roles.

**Comment by ultrasaurus** [comment]
* Dan - June 3, 2019 -  June 3, 2020
* Sarah & JJ — June 3, 2019 - June 3, 2021

@dshaw will do PR to add README where we are identified as chairs

**Comment by dshaw** [comment]
PR for Chair terms: https://github.com/cncf/sig-security/pull/279
