### ISSUE TITLE
Who is the Quota Operator?

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#32]
What was the original intent of this persona?  it seems like it might be more of a cluster of use cases that belongs to another role, rather than a job unto itself.

From reading the use cases, it seems like it is someone who works in the IT org and is responsible for managing the quota settings for their org --- in my experience, this person is sometimes responsible for checking budgets (at least understanding costs) and potentially recommending a increasing capacity  

@dshaw notes that in the public cloud, as a developer you run into situations where you need to request additional quota (from what seems like a human, but could be a bot) -- is that a different Quota Operator role?

Discussed in today's SAFE meeting, see [notes](https://docs.google.com/document/d/1fyBDIm82xtTYWhZu3gyLahltMdTOxl9aWfOfRxYHapo/edit)

**Comment by ultrasaurus** [comment]
@sreetummidi @raycolline @ckemper67 what do you think?

**Comment by ckemper67** [comment]
The intent of the persona was to go beyond restricting SAFE to pure authorization scenarios.

Note that quota is not necessarily a cost control measure. A more important use of quota is to protect your service from abuse. By setting a quota you can make sure that a single customer cannot bring down the service for everybody else (either intentionally or unintentionally). We have seen services that do not implement proper exponential backoff and a simple quota enforcement in front of your service can reduce the impact of the repeated request on the rest of your infrastructure.

The quota for cost control (i.e. a budget) is also interesting and these cost control measures could actually be administered by a different persona. I believe in GCP we call them Billing Administrators and they may have a financial, rather than an engineering background

**Comment by ultrasaurus** [comment]
Thanks @ckemper67 for your insights on this. I've submitted a PR based on your comment.  

Related to this, in the last WG meeting, we discussed proposal to validate personas with some research -- anyone viewing this, may also be interested in commenting on:  https://github.com/cn-security/safe/issues/109

**Comment by lumjjb** [comment]
Resolved by https://github.com/cncf/sig-security/pull/113
