### ISSUE TITLE
[BUG] Logo and design page colors/text not lined up when zoomed

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#344]
As pointed out in https://github.com/cncf/sig-security/pull/339#pullrequestreview-359251744

In certain cases, the words showing the hex code of colors are not matching the colored boxes.

**Comment by lumjjb** [comment]
@alexcontini

**Comment by alexcontini** [comment]
@lumjjb very sorry for the delay with this!!

I had trouble figuring out a solution as markdown doesn't support color, so I can't seem to add color with css, and the colors therefore have to be images. As a result, there seems to be limited options as markdown doesn't allow for much styling, but I have tried something that might be better - https://github.com/alexcontini/sig-security/tree/contini-fix-logo-page/logo - 

you will see I added a chart with the colors that makes it all aligned, not sure if that works better? (if I were to do this version, I would organize all color files into a folder so they aren't loose like that) I also adjusted the spacing above on the original colors and codes so that part might be fixed on your screen?

Let me know any feedback when you have a chance!

**Comment by lumjjb** [comment]
Hi @alexcontini . That looks great actually! I like it very much and I think it works well for our purposes.

I noticed that there is a misalignment between the colors and the color codes in the display, looks like an off-by-one shift. If not this looks great. Let's get this up in a PR!

**Comment by lumjjb** [comment]
Fixed by https://github.com/cncf/sig-security/pull/370
