### ISSUE TITLE
[Presentation] Proposal to launch Sandbox Project around Gluu's OAuth / OpenID / FIDO components

### ISSUE THREAD

**Issue by nynymike** [cncf/sig-security#366]
### Janssen : A Cloud Native Identity and Authorization Platform
Mike Schwartz [nynymike](https://github.com/nynymike)

We need a home to provide a community, consensus-driven governance platform for Gluu's core projects. Most in the IAM industry would agree that the Gluu Server is currently one of the best OpenID Connect implementations. According to the [published self-certification results](https://openid.net/certification/), Gluu is the only implementation to self-certify four times. It is passing all OP tests, the FAPI OP tests, and very soon, the CIBA tests as well. The Gluu Server is also the most comprehensive implementation of Kantara's User Managed Access protocol (UMA 2.0). As part of this project, Gluu would also like to contribute our implementation of FIDO and SCIM. I'm proposing "Janssen" as a new name for a CNCF sandbox project, to honor some of the most amazing athletes, pound for pound, in the world: racing pigeons! 

I've prepared slides. I'm still editing them, but the link is here: https://gluu.co/cncf-proposal

Time: How long will the presentation take? 30-45 minutes.

Availability: Any Weds at 10am works for a Zoom presentation. 

TO DO
- [x] SIG Representative: @lumjjb 
- [x] Schedule date: 15 April

**Comment by nynymike** [comment]
Just to be clear, there is zero overlap between Dex and Gluu's OAuth Authorization Server that we are proposing to make into a new project.  Dex is a federation proxy or gateway. In the Gluu Server (which is an integration of several components), we currently use Passport-js as our federation proxy. But Gluu is not the author of Passport-js and it's 100% outside the scope we would address in this proposed project.

**Comment by lumjjb** [comment]
Hi @nynymike , thanks for creating an issue, we can schedule a presentation. I suppose your availability timing syncs up with our meeting time as listed in the README[/README.md], just to clarify since the timezone wasn't specified.

For the presentation to the group, it should focus on the technicalities of the project. The next open slot is on April 8. But it looks like we have couple presentations lined up before that, so we may be due for a work session. So probably 15 April instead. (@dshaw thoughts on this?)

I noticed part of the motivation for this presentation is around submitting the project for sandbox in CNCF. Our current take on CNCF recommendations for projects is currently in process. The current trajectory discussed is that projects will go through the self-assessment as part of the evaluation of the project - which I notice your presentation has a lot of details on. A [self-assessment document](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md) should be filled out for this process. We are still fleshing out this process right now.

**Comment by nynymike** [comment]
April 15th is fine. I'm in Austin, so my timezone is CDT. I'll complete the self-assessment document. Thanks for the info.

**Comment by lumjjb** [comment]
okay, the meetings happen at 10am Pacific time, I'll put you down for April 15 then.

**Comment by lumjjb** [comment]
Presentation is completed - @nynymike can you post a link to the slides here? Tks

**Comment by nynymike** [comment]
[Mike's Proposal to move oxAuth (Janssen) to CNCF](https://gluu.co/cncf-proposal)

**Comment by lumjjb** [comment]
Great thanks!
