### ISSUE TITLE
Consider better coordination between network based security and identity based security

### ISSUE THREAD

**Issue by ckemper67** [cncf/sig-security#80]
Network security and identity based security tends to be considered in isolation. Projects like Istio are re-thinking this approach and allow you to secure the service to service communication based on service identities.

It is difficult for administrators to think about these aspects together and we should try to take that into account. Problems in this area are:
1. With ephemeral containers, providing a stable IP address as a "service identity" becomes increasingly difficult
2. In a microservice environment expressing the notion that two services can talk to one another if they are on a shared network becomes harder to manage.
3. How can we make it easy for administrators to move from an IP based to an identity based security model. 
4. Alternatively: How can we make it easy for administrators mix IP based and identity based security models.

Tigera Calico is trying to address this in their networking policy. They allow a mix of "ip based identities" and "cert based identities"

@pragashj @tk2929 thoughts?

**Comment by ckemper67** [comment]
@dshaw wanted us to define the area of concern and asses how deep we want to go in this working group.

**Comment by tk2929** [comment]
Just my loud thoughts probably echoing your issues:
IP based identity authentication may not render well in the virtualized environment: 
•	When the pods/containers fail, the substitute or standby container must assume (re-assignment aka reconfiguration) the same IP address in order to keep the authentication check transparent – not an easily scalable approach. 
•	This may become further complex if a single container app package gets migrated to microservice or serverless scattered over multiple containers or even Pods. Likely, the original IP based authentication needs to be reconfigured with multiple IP addresses. Though less frequent, avoiding such authentication reconfiguration would certainly be desirable since from user perspective application operation would remain the same while underneath virtual entities may have been changed. Similar issues come to mind if the load balancer needs to trigger additional Pods/containers.
1. Is not the service identity tied to service account (not necessarily IP based)? 
3, 4: Service identity (K8s service account) seems to be an improvement over IP identity scheme. Automation and mediation broker come to mind to perhaps help admin and scale the IP and service account mapping scheme

**Comment by lumjjb** [comment]
Closed due to inactivity.
